ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
#FROM docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}
FROM daocloud.io/library/kibana:6.4.0

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
