ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
#FROM docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}
FROM daocloud.io/library/logstash:6.4.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
